
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: project2-pv2-joaojunior
  namespace: joaojunior
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  selector:
    matchLabels:
      namespace: joaojunior
