apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: project2-pvc-joaojunior
  namespace: joaojunior
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  volumeName: project2-pv2-joaojunior  # Nome exato do PV
  storageClassName: default-storage-class-joaojunior

