apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: project2-pvc-joaojunior
  namespace: joaojunior
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  selector:
    matchLabels:
      type: local
      namespace: joaojunior
  storageClassName: default-storage-class-joaojunior
